name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2
      - name: Install project dependencies
        uses: docker://dataformco/dataform:1.16.3
        with:
          args: install
      - name: Run dataform compile
        uses: docker://dataformco/dataform:1.16.3
        with:
          args: compile
